name: Deploy
on:
  push:
    branches: [ feature/*, develop, master ]
env:
  language: 'javascript'
  CURRENT_VERSION: $(node -p "require('./package.json').version")
jobs:
  install-dependencies:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Restore or save cache for dev Dependencies
        uses: actions/cache@v2
        env:
          cache-name: npm-node-modules
        with:
          path: node_modules
          key: npm-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}-dev
      - name: Install Dependencies
        run: |
          if [ -d "node_modules" ]; then
            echo 'Dependencies already exists!'
          else
            npm i
          fi
  build:
    runs-on: ubuntu-20.04
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Restore or save cache for dev Dependencies
        uses: actions/cache@v2
        env:
          cache-name: npm-node-modules
        with:
          path: node_modules
          key: npm-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}-dev
      - name: Install Dependencies
        run: |
          npm run build
      - name: Persist Data
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
  test:
    runs-on: ubuntu-20.04
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Restore or save cache for dev Dependencies
        uses: actions/cache@v2
        env:
          cache-name: npm-node-modules
        with:
          path: node_modules
          key: npm-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}-dev
      - name: Running Linter
        run: npm run lint
      - name: Running Test
        run: |
          npm run test:coverage && npm run test:coverage:report
      - name: Persist Data
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage